### ISSUE TITLE
Error creating new character

### ISSUE THREAD

**Issue by TheGrey01** [nearbear/ValheimBepinexMods#6] opened 2021-03-07 21:30 UTC
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
CustomSlotItemLib.CustomSlotManager.IsCustomSlotItem (ItemDrop+ItemData item) (at <400d054719ed43f2a67012754fb274bf>:0)
CustomSlotItemLib.Patches.IsItemEquipedPostfix (System.Boolean& __result, Humanoid& __instance, ItemDrop+ItemData item) (at <400d054719ed43f2a67012754fb274bf>:0)
(wrapper dynamic-method) Humanoid.DMD<Humanoid::IsItemEquiped>(Humanoid,ItemDrop/ItemData)
(wrapper dynamic-method) Humanoid.DMD<Humanoid::EquipItem>(Humanoid,ItemDrop/ItemData,bool)
Humanoid.GiveDefaultItem (UnityEngine.GameObject prefab) (at <f48d6a22696245bf8d820aad6afa4fdb>:0)
Humanoid.GiveDefaultItems () (at <f48d6a22696245bf8d820aad6afa4fdb>:0)
FejdStartup.OnNewCharacterDone () (at <f48d6a22696245bf8d820aad6afa4fdb>:0)
UnityEngine.Events.InvokableCall.Invoke () (at <51725b129ecd4967a9a213c1ae65b295>:0)
UnityEngine.Events.UnityEvent.Invoke () (at <51725b129ecd4967a9a213c1ae65b295>:0)
UnityEngine.UI.Button.Press () (at <5abdc278a459476dabe36f8ad65ea091>:0)
UnityEngine.UI.Button.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at <5abdc278a459476dabe36f8ad65ea091>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at <5abdc278a459476dabe36f8ad65ea091>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at <5abdc278a459476dabe36f8ad65ea091>:0)
UnityEngine.EventSystems.EventSystem:Update()

**Comment by nearbear** [comment] 2021-03-08 01:18
I'm not able to reproduce your issue by creating a new character, mine generates no errors.

That said, I can guess the cause from the stack trace. I added some additional checks to a function in the latest version, could you please download and confirm if that fixes your issue?

Failing that, could you paste your mod list plus a description of anything you're doing beyond clicking new character, entering a name, and clicking done?

**Comment by TheGrey01** [comment] 2021-03-08 05:29
I think it was an inadvertent mod conflict.  I thought I had mod still
installed that I thought I had removed.  So if it comes back I'll let you
know.

**Comment by nearbear** [comment] 2021-03-08 05:46
Out of curiosity what mod was it?

**Comment by TheGrey01** [comment] 2021-03-08 07:43
I THINK it was the Equipment And Quick Slots mod, which btw if you could
take a look at and maybe find a way to add it's feature to your mod (it
moves equipment to it's own "location" so it doesn't take inventory space
(such as Chest, Legs, helm and belt) all have their own slot and it's got 3
"quick slots" that have key binds that you could put whatever in, potions,
tools, weapons, food, etc.  I like that mod a lot but I wanted the option
from your mod that allows for the wearing of both the belt and the wishbone.

**Comment by TheGrey01** [comment] 2021-03-08 07:44
oh and cape too, i keep forgetting about the cape

**Comment by nearbear** [comment] 2021-03-11 16:58
Integrating custom slots into the equipment slots mod is possible but nontrivial; it's something Randy and I can discuss as the modding scene matures. For now, they appear to be compatible so I'm going to close the issue but don't hesitate to reopen it if you can readily reproduce the error.

**Closed as completed by nearbear** 2021-03-11 16:58 UTC
